import type { Metadata } from "next"

import { sans } from "@/fonts"
import "./globals.css"

export const metadata: Metadata = {
  title: "Frontend Mentor | NFT Preview Card Component",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${sans.className} `}>{children}</body>
    </html>
  )
}
