import type { Metadata } from "next"

import { sans } from "@/fonts"
import "./globals.css"

export const metadata: Metadata = {
  title: "Frontend Mentor | NFT Preview Card Component",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.className} flex min-h-screen flex-col items-center justify-center p-6 bg-neutral-body-bg text-neutral-white`}
      >
        {children}
      </body>
    </html>
  )
}
